### ISSUE TITLE
🔔 [aiohttp][yarl] Downstream notification: a brand-new dependency

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/propcache#52]
Hey @hroncok & @mgorny!

This is a new dependency of `aiohttp` and `yarl`. It's currently packaged similarly to `yarl` so you should be able to copy the existing RPM spec and ebuild from there with minimal adjustments. It's already been added to the dependencies in some places already.

JFYI.

**Comment by webknjaz** [comment]
I just did an `eix-sync` and saw that it's in portage already. And Miro thumbed up the issue, so I'm closing it now.

**Comment by hroncok** [comment]
FWIW I do not maintain aiohttp or yarl in Fedora. I thumbed up the issue as a thank you.
